
nuxt-app:
	npm create nuxt@latest
	cd nuxt-app && npm install 
	cd nuxt-app && npm install -D @nuxtjs/tailwindcss
	cd nuxt-app && npm install primevue primeicons
	cp -r ./pages ./nuxt-app
	cp -r ./components ./nuxt-app
	cp -r ./assets ./nuxt-app
	mv nuxt.config.ts ./nuxt-app

clean:
	rm -rf nuxt-app
